set_property SRC_FILE_INFO {cfile:{C:/Users/user/Documents/nguyen vivado/blink/blink.srcs/constrs_1/new/blinkconst.xdc} rfile:../../../blink.srcs/constrs_1/new/blinkconst.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports o_led]
