set_property SRC_FILE_INFO {cfile:{C:/Users/user/Documents/nguyen vivado/debouncer/debouncer.srcs/constrs_1/new/dbconst.xdc} rfile:../../../debouncer.srcs/constrs_1/new/dbconst.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports pb_1]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports pb_out]
